<?php

/**
 * @file
 * Contains d8_card_17.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_card_17_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_card_17 module.
    case 'help.page.d8_card_17':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 card day 17') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8_card_17_theme() {
  return [
    'd8_card_17' => [
      'render element' => 'children',
    ],
  ];
}
