id: genres
label: Genres
migration_group: demo
source:
  plugin: genres
  key: default
destination:
  plugin: 'entity:taxonomy_term'
process:
  vid:
    plugin: default_value
    default_value: genre
  name: name
_core:
  default_config_hash: jRy6G22GkRfdIZjnUrwmOwnTooDn2HIIuaKxrLIsYo8
